[package]
name = "jerevuola"
version = "0.2.1"
edition = "2021"

[dependencies]
yew = "0.19.3"


# wasm binary optimizations
[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true
