[build]
target = "index.html"
dist = "dist"
release = false
public_url = "/"
# public_url = "/{project_name}/"            # for {username}.github.io/{project_name}
# public_url = "/"                           # for {username}.github.io

[watch]
watch = [
    "./index.html",
    "src/",
    "static/",
]

[clean]
dist = "dist"

